export const languageOptions = [
    {
        id: 1,
        name: "Assembly (NASM 2.14.02)",
        label: "Assembly (NASM 2.14.02)",
        value: "assembly",
    },
    {
        id: 2,
        name: "Bash (5.0.0)",
        label: "Bash (5.0.0)",
        value: "bash",
    },
    {
        id: 3,
        name: "Basic (FBC 1.07.1)",
        label: "Basic (FBC 1.07.1)",
        value: "basic",
    },
    {
        id: 4,
        name: "C (GCC 9.2.0)",
        label: "C (GCC 9.2.0)",
        value: "C",
    },
    {
        id: 5,
        name: "C# (Mono 6.6.0.161)",
        label: "C# (Mono 6.6.0.161)",
        value: "c#",
    },
    {
        id: 6,
        name: "C++ (GCC 9.2.0)",
        label: "C++ (GCC 9.2.0)",
        value: "c++",
    },
    {
        id: 7,
        name: "Clojure (1.10.1)",
        label: "Clojure (1.10.1)",
        value: "clojure",
    },
    {
        id: 8,
        name: "COBOL (GnuCOBOL 2.2)",
        label: "COBOL (GnuCOBOL 2.2)",
        value: "cobol",
    },
    {
        id: 9,
        name: "Common Lisp (SBCL 2.0.0)",
        label: "Common Lisp (SBCL 2.0.0)",
        value: "lisp",
    },
    {
        id: 10,
        name: "D (DMD 2.089.1)",
        label: "D (DMD 2.089.1)",
        value: "d",
    },
    {
        id: 11,
        name: "Elixir (1.9.4)",
        label: "Elixir (1.9.4)",
        value: "elixir",
    },
    {
        id: 12,
        name: "Erlang (OTP 22.2)",
        label: "Erlang (OTP 22.2)",
        value: "erland",
    },
    {
        id: 13,
        name: "Executable",
        label: "Executable",
        value: "exe",
    },
    {
        id: 14,
        name: "F# (.NET Core SDK 3.1.202)",
        label: "F# (.NET Core SDK 3.1.202)",
        value: "f#",
    },
    {
        id: 15,
        name: "Fortran (GFortran 9.2.0)",
        label: "Fortran (GFortran 9.2.0)",
        value: "fortran",
    },
    {
        id: 16,
        name: "Go (1.13.5)",
        label: "Go (1.13.5)",
        value: "go",
    },
    {
        id: 17,
        name: "Groovy (3.0.3)",
        label: "Groovy (3.0.3)",
        value: "groovy",
    },
    {
        id: 18,
        name: "Haskell (GHC 8.8.1)",
        label: "Haskell (GHC 8.8.1)",
        value: "haskell",
    },
    {
        id: 19,
        name: "Java (OpenJDK 13.0.1)",
        label: "Java (OpenJDK 13.0.1)",
        value: "java",
    },{
        id: 20,
        name: "JavaScript (Node.js 12.14.0)",
        label: "JavaScript (Node.js 12.14.0)",
        value: "js",
    },{
        id: 21,
        name: "Kotlin (1.3.70)",
        label: "Kotlin (1.3.70)",
        value: "kotlin",
    },
    {
        id: 22,
        name: "Lua (5.3.5)",
        label: "Lua (5.3.5)",
        value: "lua",
    },
    {
        id: 23,
        name: "Objective-C (Clang 7.0.1)",
        label: "Objective-C (Clang 7.0.1)",
        value: "obj-c",
    },
    {
        id: 24,
        name: "OCaml (4.09.0)",
        label: "OCaml (4.09.0)",
        value: "ocaml",
    },
    {
        id: 25,
        name: "Octave (5.1.0)",
        label: "Octave (5.1.0)",
        value: "octave",
    },
    {
        id: 26,
        name: "Pascal (FPC 3.0.4)",
        label: "Pascal (FPC 3.0.4)",
        value: "pascal",
    },
    {
        id: 27,
        name: "Perl (5.28.1)",
        label: "Perl (5.28.1)",
        value: "perl",
    },
    {
        id: 28,
        name: "PHP (7.4.1)",
        label: "PHP (7.4.1)",
        value: "php",
    },
    {
        id: 29,
        name: "Plain Text",
        label: "Plain Text",
        value: "txt",
    },
    {
        id: 30,
        name: "Prolog (GNU Prolog 1.4.5)",
        label: "Prolog (GNU Prolog 1.4.5)",
        value: "prolog",
    },
    {
        id: 31,
        name: "Python (3.8.1)",
        label: "Python (3.8.1)",
        value: "python",
    },
    {
        id: 32,
        name: "R (4.0.0)",
        label: "R (4.0.0)",
        value: "r",
    },{
        id: 33,
        name: "Ruby (2.7.0)",
        label: "Ruby (2.7.0)",
        value: "ruby",
    },
    {
        id: 34,
        name: "Rust (1.40.0)",
        label: "Rust (1.40.0)",
        value: "rust",
    },
    {
        id: 35,
        name: "Scala (2.13.2)",
        label: "Scala (2.13.2)",
        value: "scala",
    },
    {
        id: 36,
        name: "SQL (SQLite 3.27.2)",
        label: "SQL (SQLite 3.27.2)",
        value: "sql",
    },
    {
        id: 37,
        name: "Swift (5.2.3)",
        label: "Swift (5.2.3)",
        value: "swift",
    },
    {
        id: 38,
        name: "TypeScript (3.7.4)",
        label: "TypeScript (3.7.4)",
        value: "ts",
    },
    {
        id: 39,
        name: "Visual Basic.Net (vbnc 0.0.0.5943)",
        label: "Visual Basic.Net (vbnc 0.0.0.5943)",
        value: "v-basic",
    },
];